# Generated by Django 5.1.1 on 2024-10-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Captcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('transport', 'Transport'), ('payment', 'Payment')], max_length=10)),
                ('image', models.ImageField(upload_to='captcha_images')),
                ('solution', models.BooleanField(default=False)),
            ],
        ),
    ]
